### ISSUE TITLE
Support for wordmark logos?

### ISSUE THREAD

**Issue by chrismessina** [soulchild/sketch-logo-fetcher#2]
I was so hoping someone might have built this kind of plugin! Thank you!

Any thoughts on making it possible to pull down SVG versions of logo wordmarks instead of just app icons?

**Comment by soulchild** [comment]
Thanks! I'm glad you like my plugin. 😄

I'd love to have the company logos in SVG format, but unfortunately the [ClearBit API](https://clearbit.com/logo) which is used by the plugin only offers bitmaps. 😞 If you come across a (free) API which delivers SVG logos, I'd be more than happy to update the plugin.

**Comment by chrismessina** [comment]
Ok! I'd settle for the ability to crowd source logos...

**Comment by soulchild** [comment]
I'm working on an extension which will allow inserting SVG logos from various sources (currently there's only support for [svgporn](https://github.com/gilbarbara/logos)). The first step is my attempt at a [RESTful Logos API](https://github.com/soulchild/logos-api). 
Next, I'll need to figure out a way to insert SVGs into Sketch documents which still seems to be adventurous territory. 😄

**Comment by soulchild** [comment]
If you want, you can give the [logos-api branch](https://github.com/soulchild/sketch-logo-fetcher/tree/logos-api) a try. The basic functionality is there, it just needs a little bit more polishing. Let me know what you think!

**Comment by soulchild** [comment]
I've since merged the logos-api branch and shipped v0.3.0 which you can get from the [releases page](https://github.com/soulchild/sketch-logo-fetcher/releases/tag/v0.3.0). Looking forward to hearing some feedback! I'll close this issue for now.
