### ISSUE TITLE
This doesn't seem to work on Sketch v 41.2

### ISSUE THREAD

**Issue by ayezee33** [soulchild/sketch-logo-fetcher#3]
I am not seeing anything happening when I follow the docs. Anyone else having an issue?

**Comment by soulchild** [comment]
That's odd. Are you seeing the plugin in the menu? I'll have to wait until Monday before I can take a look at it.

**Comment by soulchild** [comment]
Just verified that it's working with Sketch 41.2. What exactly is failing on your end?

**Comment by soulchild** [comment]
I'm closing this for now. Feel free to re-open the issue with more detailed information, if you're still having trouble getting it to work.
