### ISSUE TITLE
Query error when company name is more than one word

### ISSUE THREAD

**Issue by t1wk** [soulchild/sketch-logo-fetcher#5]
Hi!

First of all, kudos for this plugin, it's a time saver! It seems that the API doesn't handle correctly query that has more than one word.

I was looking for JP Morgan, Ralph Lauren, and Vitamin Shoppe. All of them said there was an error in the query. It seems to go through when you use %20 instead of a space, but not every Sketch user is also a developer.

My 2 cents!

**Comment by soulchild** [comment]
Good catch! I'll try to provide a bug fix asap.

**Comment by soulchild** [comment]
Should be fixed in [release v0.5.7](https://github.com/soulchild/sketch-logo-fetcher/releases/tag/v0.5.7). Thanks for reporting the issue!
