### ISSUE TITLE
0.5.8 - After downloading the plug to update, it doesn't install because it says it's version 0.5.7

### ISSUE THREAD

**Issue by ikowilson** [soulchild/sketch-logo-fetcher#6]

**Comment by soulchild** [comment]
Whoops, I forgot to bump the version in the `manifest.json`. I removed `v0.5.8` and released `v0.5.9` which should work correctly. Thanks for pointing out!

**Comment by ikowilson** [comment]
🙌🏼 Got it working. But I had to download it directly from git to install. You'll need to look into how to get the update working from within Slack / Preferences / Plugins. The issue still persists if you try to update in the menu.

**Comment by soulchild** [comment]
Thanks for letting me know. I deleted the plugin in Sketch, installed the previous version `v0.5.7` and had no trouble using the Sketch upgrade process to go to the latest `v0.5.9`. If you don't mind, I'd close this issue for now and see if others have similar issues before investigating any further. Ok?
